version: "3"

services:
  postgres:
    image: postgres:9.2
    container_name: fraud-database-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - TZ=GMT
    volumes:
      - "./data/frauds/postgres:/var/lib/postgres/data"
    ports:
      - 5434:5434